export const color = [
  "Black",
  "White",
  "Blue",
  "Navy Blue",
  "Sky Blue",
  "Red",
  "Maroon",
  "Green",
  "Olive",
  "Light Green",
  "Yellow",
  "Mustard",
  "Orange",
  "Pink",
  "Purple",
  "Brown",
  "Grey",
  "Beige",
  "Cream",
  "Gold",
];

export const filters = [
  {
    id: "color",
    name: "Color",
    options: [
      { value: "Black", label: "Black" },
      { value: "White", label: "White" },
      { value: "Blue", label: "Blue" },
      { value: "Navy Blue", label: "Navy Blue" },
      { value: "Sky Blue", label: "Sky Blue" },
      { value: "Red", label: "Red" },
      { value: "Maroon", label: "Maroon" },
      { value: "Green", label: "Green" },
      { value: "Olive", label: "Olive" },
      { value: "Light Green", label: "Light Green" },
      { value: "Yellow", label: "Yellow" },
      { value: "Mustard", label: "Mustard" },
      { value: "Orange", label: "Orange" },
      { value: "Pink", label: "Pink" },
      { value: "Purple", label: "Purple" },
      { value: "Brown", label: "Brown" },
      { value: "Grey", label: "Grey" },
      { value: "Beige", label: "Beige" },
      { value: "Cream", label: "Cream" },
      { value: "Gold", label: "Gold" },
    ],
  },
  {
  id: "size",
  name: "Size",
  options: [
    { value: "S", label: "S" },
    { value: "M", label: "M" },
    { value: "L", label: "L" },
  ],
}
];

export const singleFilter = [
  {
    id: "price",
    name: "Price",
    options: [
      { value: "159 - ₹399", label: "₹159 - ₹399" },
      { value: "400 - ₹699", label: "₹400 - ₹699" },
      { value: "700 - ₹999", label: "₹700 - ₹999" },
      { value: "1000 - ₹1499", label: "₹1000 - ₹1499" },
      { value: "1500 - ₹1999", label: "₹1500 - ₹1999" },
      { value: "2000 - ₹2499", label: "₹2000 - ₹2499" },
      { value: "2500 - ₹2999", label: "₹2500 - ₹2999" },
      { value: "3000 - ₹3999", label: "₹3000 - ₹3999" },
      { value: "4000 - ₹4999", label: "₹4000 - ₹4999" },
      { value: "5000+", label: "₹5000 & Above" },
    ],
  },
  {
  id: "discount",
  name: "Discount Range",
  options: [
    { value: 10, label: "10% & Above" },
    { value: 20, label: "20% & Above" },
    { value: 30, label: "30% & Above" },
    { value: 40, label: "40% & Above" },
    { value: 50, label: "50% & Above" },
    { value: 60, label: "60% & Above" },
    { value: 70, label: "70% & Above" },
    { value: 80, label: "80% & Above" },
    { value: 90, label: "90% & Above" },
  ],
},
];